### Variables
@base_url = http://localhost:4000

###
get {{base_url}}/contacts?owner=1652453601609658
Content-Type: application/json

###
post {{base_url}}/contacts
Content-Type: application/json

{
    "owner": 1234,
    "contact_list":[
        {
            "id": 1234,
            "lookUp": 1234,
            "name": "Park Sang June",
            "number": "01082633554",
            "thumb": "dfadsfa21323123@%$#@"
        },
        {
            "id": 1235,
            "lookUp": 1235,
            "name": "Lee Kang Uk",
            "number": "01024717875",
            "thumb": "ddkfj1@#!24jdfjlasdk"
        },
        {
            "id": 1236,
            "lookUp": 1236,
            "name": "Dummy",
            "number": "0107777777",
            "thumb": "ddkfj1@#!24jdfjlasdk"
        }
    ]
}

###
get {{base_url}}/gallery/image_list?owner=1234
Content-Type: application/json

###
POST {{base_url}}/gallery/image_list
Content-Type: application/json

{
    "owner":1234,
    "image_list":[
        {
            "type": 1,
            "fd": "조조 초상화",
            "bitmap": "dkfjldjfl231lj23j1lj4##!@#"
        },
        {
            "type": 0,
            "fd": "하후돈 초상화",
            "bitmap": null
        }
    ]
}

### 
get {{base_url}}/gallery/structure?owner=1234
Content-Type: application/json

###
POST {{base_url}}/gallery/structure
Content-Type: application/json

{
    "owner":1234,
    "structure":{
        "children": [
            {
                "children": [],
                "dirName": "",
                "imgAddr": 1,
                "type": 0
            }
        ],
        "dirName": "하위",
        "imgAddr": 5,
        "type": 0
    }
}

###
GET {{base_url}}/gallery/all?owner=1234
Content-Type: application/json

###
POST {{base_url}}/gallery/all
Content-Type: application/json

{
    "owner":1234,
    "image_list": [
          {
            "type": 0,
            "fd": 1,
            "bitmap": null
          },
          {
            "type": 0,
            "fd": 2,
            "bitmap": null
          }
    ],
    "structure":{
        "children": [
            {
                "children": [],
                "dirName": "",
                "imgAddr": 1,
                "type": 0
            }
        ],
        "dirName": "",
        "imgAddr": 5,
        "type": 0
    }
}